# check installation, install and load dependencies

library(shiny)
library(edgeR)
library(ggplot2)
library(pheatmap)
library(ggrepel)
library(pheatmap)
library(Seurat)
library(DESeq2)
library(RColorBrewer)
library(readxl)
library(ggsignif)
library(DT)
library(graphics)
library(enrichplot)
library(ggpubr)
library(ggprism)
library(patchwork)
